
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - TZ=Asia/Bangkok
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
      - wordpress-config:/etc/apache2
    networks:
      - wordpress-network
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "wordpress"
  db:
    image: mariadb:11.4
    container_name: db
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=wordpress
    volumes:
      - db:/var/lib/mysql
      - db-config:/etc/mysql/conf.d
    networks:
      - wordpress-network
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "mariadb"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=1024M
    ports:
      - 8081:80
    networks:
      - wordpress-network
volumes:
  wordpress:
  wordpress-config:
  db:
  db-config:

networks:
  wordpress-network:
